# Fly.io configuration for AI Booking Agent Backend
app = "your-booking-agent-backend"
primary_region = "iad"  # Change to your preferred region

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  API_RELOAD = "false"
  USE_MOCK_CALENDAR = "true"
  LOG_LEVEL = "INFO"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

# Add your environment variables here
# [env]
#   OPENAI_API_KEY = "your-openai-api-key"
#   ANTHROPIC_API_KEY = "your-anthropic-api-key"
#   SMTP_HOST = "your-smtp-host"
#   SMTP_USERNAME = "your-smtp-username"
#   SMTP_PASSWORD = "your-smtp-password"
#   FROM_EMAIL = "noreply@yourdomain.com"
#   SECRET_KEY = "your-secret-key" 