version: '3.8'
services:
  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
      - ./credentials:/credentials
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials/google_credentials.json
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    command: streamlit run streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    volumes:
      - ./frontend:/app
    ports:
      - "8501:8501"
    depends_on:
      - backend
  redis:
    image: redis:7
    ports:
      - "6379:6379" 